## PowerShell Script to conveniently open in a browser the
## HTML documentation which was generated by Doxygen.
##
## @file        open-doxygen-html-docs.ps1
## @author      Lester J. Dowling
## @date        Started 2019-04-21
Param
(
	[parameter(mandatory = $false)]
    [Switch]
    [alias("q")]
    $QUIET
)

#
# Audio Player
#
New-Variable -Name AUDIO -Scope Script -Force
if (-Not($QUIET)) {
    $AUDIO = New-Object System.Media.SoundPlayer
}

#
# Sounds Directory
#
New-Variable -Name SOUNDS_DIR  -Scope Script -Force
[string] $SOUNDS_DIR = Resolve-Path "${ENV:USERPROFILE}/sounds" -ea:ignore    |    Select -ExpandProperty Path


Function fatal_error_exit($ERROR_MESSAGE) {   # Fatal error; cannot continue.
    if (-Not($QUIET)) {
        $ERROR_SOUND = Resolve-Path "${SOUNDS_DIR}/Computer-Data-Error-Sound.wav" -ea:ignore    |    Select -ExpandProperty Path
        if (Test-Path $ERROR_SOUND) {
            $AUDIO.SoundLocation = "$ERROR_SOUND"
	        $AUDIO.Play()
        }
    }
    Write-Output "!!! [ERROR] $ERROR_MESSAGE"
    Write-VolumeCache C
    exit 1
}

#
# MAIN
#
if (-Not(Test-Path "${PSScriptRoot}cmake_binary_dir.txt")) {
    fatal_error_exit "Build the project before viewing the docs."
}
$BINARY_DIR = Get-Content "${PSScriptRoot}cmake_binary_dir.txt"
$BINARY_DIR = Resolve-Path "${BINARY_DIR}" -ErrorAction:Ignore
if (-Not(Test-Path $BINARY_DIR)) {
	fatal_error_exit "No such CMake binary directory: $BINARY_DIR"
}
$INDEX_HTML = Resolve-Path "${BINARY_DIR}/html/index.html" -ErrorAction:Ignore

if (-Not(Test-Path $INDEX_HTML)) {
	fatal_error_exit "No such HTML file: $INDEX_HTML"
}

start "$INDEX_HTML"
